### ISSUE TITLE
No module named 'torch_int'

### ISSUE THREAD

**Issue by kaust2018** [mit-han-lab/smoothquant#41]
Traceback (most recent call last):
  File "examples/export_int8_model.py", line 10, in <module>
    from smoothquant.opt import Int8OPTForCausalLM
  File "<frozen zipimport>", line 259, in load_module
  File "/root/anaconda3/envs/smoothquant/lib/python3.8/site-packages/smoothquant-0.0.0-py3.8.egg/smoothquant/opt.py", line 15, in <module>
ModuleNotFoundError: No module named 'torch_int'

**Comment by amazingkmy** [comment]
install torch-int
https://github.com/Guangxuan-Xiao/torch-int

**Comment by kaust2018** [comment]
> install torch-int https://github.com/Guangxuan-Xiao/torch-int

Thanks for pointing this out, but it only works in Cuda 11.3 environment? Failed to run bash build_cutlass.sh when I was using cuda12.1

**Comment by amazingkmy** [comment]
@kaust2018 
check this repo
https://github.com/NVIDIA/cutlass

I didn't know that.. maybe you can do this

**Comment by breaddance** [comment]
@amazingkmy  I found that I can't install the "torch_int" code library. Do you have a solution? If you do, I would be extremely grateful. 
 × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/root/paddlejob/suzaolin/torch-int-main/setup.py", line 2, in <module>
          from torch.utils import cpp_extension
        File "/opt/conda/envs/smoothquant/lib/python3.8/site-packages/torch/__init__.py", line 778, in <module>
          _C._initExtension(manager_path())
      AttributeError: partially initialized module 'torch' has no attribute 'UntypedStorage' (most likely due to a circular import)

**Comment by kaust2018** [comment]
> @amazingkmy I found that I can't install the "torch_int" code library. Do you have a solution? If you do, I would be extremely grateful. × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [8 lines of output] Traceback (most recent call last): File "", line 2, in File "", line 34, in File "/root/paddlejob/suzaolin/torch-int-main/setup.py", line 2, in from torch.utils import cpp_extension File "/opt/conda/envs/smoothquant/lib/python3.8/site-packages/torch/**init**.py", line 778, in _C._initExtension(manager_path()) AttributeError: partially initialized module 'torch' has no attribute 'UntypedStorage' (most likely due to a circular import)

**Use docker to install exactly the libraries and cuda version as stated in the repo.**

**Comment by SoYuCry** [comment]
The same:

(Standard) F:\Liuc\smoothquant-main>D:/anaconda/envs/Standard/python.exe f:/Liuc/smoothquant-main/temp.py
Traceback (most recent call last):
  File "f:/Liuc/smoothquant-main/temp.py", line 1, in <module>
    from smoothquant.opt import Int8OPTForCausalLM
  File "f:\Liuc\smoothquant-main\smoothquant\opt.py", line 15, in <module>
    from torch_int.nn.linear import W8A8BFP32OFP32Linear, W8A8B8O8Linear, W8A8B8O8LinearReLU
ModuleNotFoundError: No module named 'torch_int'

**Comment by yugezheng** [comment]
> The same:
> 
> (Standard) F:\Liuc\smoothquant-main>D:/anaconda/envs/Standard/python.exe f:/Liuc/smoothquant-main/temp.py Traceback (most recent call last): File "f:/Liuc/smoothquant-main/temp.py", line 1, in from smoothquant.opt import Int8OPTForCausalLM File "f:\Liuc\smoothquant-main\smoothquant\opt.py", line 15, in from torch_int.nn.linear import W8A8BFP32OFP32Linear, W8A8B8O8Linear, W8A8B8O8LinearReLU ModuleNotFoundError: No module named 'torch_int'

Have you solved the problem yet?I meet the same one.
